# Generated by Django 5.2.3 on 2025-06-25 16:19

import curseguridad.storage_backends
import cursos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=curseguridad.storage_backends.MediaStorage(), upload_to=cursos.models.archivo_upload_path)),
                ('tipo', models.CharField(choices=[('pptx', 'PowerPoint'), ('pdf', 'PDF'), ('docx', 'Word'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='cursos.curso')),
            ],
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
    ]
