# Generated by Django 5.2.3 on 2025-06-29 06:45

import curseguridad.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_precio_cursocomprado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='video',
            field=models.FileField(blank=True, help_text='Video obligatorio que debe ver el usuario antes de acceder al contenido', null=True, storage=curseguridad.storage_backends.MediaStorage(), upload_to='videos/'),
        ),
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cursos.preguntaexamen')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_visto', models.BooleanField(default=False)),
                ('examen_aprobado', models.BooleanField(default=False)),
                ('fecha_examen', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
