# Generated by Django 5.2.3 on 2025-06-29 21:05

import curseguridad.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_video_preguntaexamen_opcionrespuesta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion_examen_minutos',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='progresocurso',
            name='en_examen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresocurso',
            name='intentos_examen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresocurso',
            name='tiempo_inicio_examen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CertificadoDC3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, storage=curseguridad.storage_backends.MediaStorage(), upload_to='certificados/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
