# Generated by Django 5.2.3 on 2025-06-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_duracion_examen_minutos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionrespuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='preguntaexamen',
            name='curso',
        ),
        migrations.AlterUniqueTogether(
            name='progresocurso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progresocurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='progresocurso',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracion_examen_minutos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='video',
        ),
        migrations.DeleteModel(
            name='CertificadoDC3',
        ),
        migrations.DeleteModel(
            name='OpcionRespuesta',
        ),
        migrations.DeleteModel(
            name='PreguntaExamen',
        ),
        migrations.DeleteModel(
            name='ProgresoCurso',
        ),
    ]
