# Generated by Django 5.2.3 on 2025-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_curso_video_examen_intentoexamen_preguntaexamen_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progresocurso',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progresocurso',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='progresocurso',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresocurso',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresocurso',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='progresocurso',
            name='video_visto_completo',
        ),
    ]
