# Generated by Django 5.2.3 on 2025-07-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_progresocurso_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='pagado',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
