# Generated by Django 5.2.3 on 2025-07-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_remove_perfilusuario_pagado_perfilusuario_curp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresocurso',
            name='video_visto_completo',
            field=models.BooleanField(default=False),
        ),
    ]
