# Generated by Django 5.2.3 on 2025-07-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_progresocurso_video_visto_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido_materno',
            field=models.CharField(default='(Sin apellido materno)', max_length=150),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido_paterno',
            field=models.CharField(default='(Sin apellido paterno)', max_length=150),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(default='(Sin nombre)', max_length=150),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='curp',
            field=models.CharField(default='(sin curp)', max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='puesto',
            field=models.CharField(default='(sin puesto)', max_length=100),
            preserve_default=False,
        ),
    ]
