# Generated by Django 5.2.3 on 2025-07-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresocurso',
            name='porcentaje_examen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
